#developement server port
server:
  port: 8085


#database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root

#jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
